---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: persistant
provisioner: kubernetes.io/rbd
reclaimPolicy: Retain
parameters:
  # change the monitors to match your IP addresses of your ceph mon nodes
  monitors:  172.31.21.245:6789,172.31.34.174:6789,172.31.75.222:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
